language: php

matrix:
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4snapshot
    allowed_failures:
        - php: nightly

before_install:
    - composer self-update
    - sudo locale-gen en_US.UTF-8 && sudo update-locale

install:
    - composer --prefer-dist install

script:
    - bin/phpspec run
